name: Deploy automation runbooks
on: [push]
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_MG }}
          enable-AzPSSession: true

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      # - name: install python packages
      #   run: |
      #     pip install azure-cli
      #     pip install azure.identity
      #     pip install python-dotenv
          

      # - name: execute py script # run policy_assignment.py
      #   env:
      #     SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
      #     WORKSPACE_ID: ${{ vars.WORKSPACE_ID }}
      #     RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
      #     ASSIGNMENT_LOCATION: ${{ vars.ASSIGNMENT_LOCATION }}
      #     MANAGEMENT_GROUP: ${{ vars.MANAGEMENT_GROUP }}
      #   run: 
      #       python policy_assignments_mg.py
      #   working-directory: scripts_mg


      # # Deploy runbooks
      # - name: Deploy Azure runbooks
      #   uses: azure/powershell@v1
      #   with:
      #     inlineScript: |       
      #       pushd ./scripts_mg
      #       Import-AzAutomationRunbook -AutomationAccountName ${{ vars.AUTOMATION_ACCOUNT_NAME }} -Name ${{ vars.RUNBOOK_NAME }} -Path remediation_task_runbook_mg.ps1 -Published -ResourceGroupName ${{ vars.RESOURCE_GROUP }} -Type PowerShell
      #       popd
      #     azPSVersion: "latest"    


      # Create And link runbook to schedule
      - name: role assignment
        uses: azure/powershell@v1
        with:
          inlineScript: |
            New-AzRoleAssignment -ObjectId 'af3790d3-869e-4582-b72a-fe020311d392' -RoleDefinitionName 'Reader and Data Access' -Scope '/providers/Microsoft.Management/managementGroups/moon-test'
          azPSVersion: "latest"


      # Logout
      - name: logout
        run: |
          az logout