# This workflow deploys Azure automation runbooks into Azure.
name: Deploy automation runbooks
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      # Deploy runbooks
      - name: Deploy Azure runbooks
        uses: azure/powershell@v1
        with:
          inlineScript: |
            pushd ./scripts
            Import-AzAutomationRunbook -AutomationAccountName 'tryingCT' -Name 'createRemediationTaskRunbook' -Path remediation_task_runbook.ps1 -Published -ResourceGroupName 'cloud-shell-storage-westeurope' -Type PowerShell
            popd
          azPSVersion: "latest"    

      # Create And link runbook to schedule
      - name: Link Runbook To Schedule
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $TimeZone = ([System.TimeZoneInfo]::Local).Id
            New-AzAutomationSchedule -AutomationAccountName "tryingCT" -Name "githubaction" -StartTime "5/03/2024 15:05:00" -DayInterval 1 -TimeZone $TimeZone -ResourceGroupName "cloud-shell-storage-westeurope"
            Register-AzAutomationScheduledRunbook -AutomationAccountName "tryingCT" -RunbookName "createRemediationTaskRunbook" -ScheduleName "githubaction" -ResourceGroupName "cloud-shell-storage-westeurope"
          azPSVersion: "latest"


      # Logout
      - name: logout
        run: |
          az logout
