# This workflow deploys Azure automation runbooks into Azure.
name: Deploy automation runbooks
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true


      # - name: setup python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' # install the python version needed

      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pip install azure-cli

      # - name: execute py script # run main.py
      #   run: python policy_assignment.py


      # Deploy runbooks
      - name: Deploy Azure runbooks
        uses: azure/powershell@v1
        with:
          inlineScript: |       
            pushd ./scripts
            Import-AzAutomationRunbook -AutomationAccountName 'moon-dev' -Name 'createRemediationTaskRunbookPolicy' -Path remediation_task_runbook.ps1 -Published -ResourceGroupName 'DefaultResourceGroup-EUS' -Type PowerShell
            popd
          azPSVersion: "latest"    

      # Create And link runbook to schedule
      - name: Create And Link Runbook To Schedule
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $TimeZone = 'Asia/Jerusalem'
            $ResourceGroupName = "DefaultResourceGroup-EUS"
            $ScheduleName = "scheduleToPolicyRunbook"
            $AutomationAccountName = "automation-account-dev"
            $params =  @{"identity"="af3790d3-869e-4582-b72a-fe020311d392","subscription"="MOON-NM-DIG-DEV"}
            New-AzAutomationSchedule -AutomationAccountName $AutomationAccountName -Name $ScheduleName -StartTime "03/08/2024 10:00:00" -DayInterval 1 -TimeZone $TimeZone -ResourceGroupName $ResourceGroupName
            Register-AzAutomationScheduledRunbook -AutomationAccountName $AutomationAccountName -Parameters $params -RunbookName "createRemediationTaskRunbook" -ScheduleName $ScheduleName -ResourceGroupName $ResourceGroupName
          azPSVersion: "latest"


      # Logout
      - name: logout
        run: |
          az logout
