# This workflow deploys Azure automation runbooks into Azure.
name: Deploy automation runbooks
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      

      # link runbook to schedule
      - name: Link Runbook To Schedule
        uses: azure/powershell@v1
        with:
          inlineScript: |
            New-AzAutomationSchedule -AutomationAccountName "tryingCT" -Name "githubaction" -StartTime "5/03/2024 14:37:00" -DayInterval 1 -TimeZone 'Israel' -ResourceGroupName "cloud-shell-storage-westeurope"
          azPSVersion: "latest"


      # Logout
      - name: logout
        run: |
          az logout
