# This workflow deploys Azure automation runbooks into Azure.
name: Deploy Kontext automation runbooks
on:
  # push:
  #   branches: ["master"]
    # paths:
    #   - "scripts/automation/**"
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      # Deploy runbooks
      - name: Deploy Azure runbooks
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Import-AzAutomationRunbook -AutomationAccountName 'tryingCT' -Name 'deploypolicyrunbook' -Path ./scripts/runbooks/myrunbook.ps1 -Published -ResourceGroupName 'cloud-shell-storage-westeurope' -Type PowerShell
            popd
          azPSVersion: "latest"
      # Logout
      - name: logout
        run: |
          az logout
