# This workflow deploys Azure automation runbooks into Azure.
name: Deploy automation runbooks
on:
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS2 }}
      #     enable-AzPSSession: true

      # - name: login to azure
      #   uses: azure/powershell@v1
      #   with:
      #     inlineScript: |
      #       $identity = "af3790d3-869e-4582-b72a-fe020311d392"
      #       $AzureContext = (Connect-AzAccount -Identity -AccountId $identity).context
      #       $connectionResult = Set-AzContext -Subscription $subscription -DefaultProfile $AzureContext
      #     azPSVersion: "latest"

      - name: login
        run: |
          az login 


      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          pip install azure-cli
          pip install azure.identity
          pip install python-dotenv
          

      - name: execute py script # run policy_assignment.py
        run: 
            python policy_assignments.py
        working-directory: scripts


      # Deploy runbooks
      - name: Deploy Azure runbooks
        uses: azure/powershell@v1
        with:
          inlineScript: |       
# pushd ./scripts
            Import-AzAutomationRunbook -AutomationAccountName 'moon-dev' -Name 'createRemediationTaskRunbookPolicy' -Path remediation_task_runbook.ps1 -Published -ResourceGroupName 'DefaultResourceGroup-EUS' -Type PowerShell
            popd
          azPSVersion: "latest"    

      # Create And link runbook to schedule
      - name: Create And Link Runbook To Schedule
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $TimeZone = 'Asia/Jerusalem'
            $ResourceGroupName = "DefaultResourceGroup-EUS"
            $ScheduleName = "scheduleToPolicyRunbook"
            $AutomationAccountName = "moon-dev"
            $params =  @{"identity"="${{ secrets.AUTOMATION_ACCOUNT_IDENTITY }}";"subscription"="MOON-NM-DIG-DEV"}
            New-AzAutomationSchedule -AutomationAccountName $AutomationAccountName -Name $ScheduleName -StartTime "05/19/2024 10:45:00" -HourInterval 1 -TimeZone $TimeZone -ResourceGroupName $ResourceGroupName
            Register-AzAutomationScheduledRunbook -AutomationAccountName $AutomationAccountName -Parameters $params -RunbookName "createRemediationTaskRunbookPolicy" -ScheduleName $ScheduleName -ResourceGroupName $ResourceGroupName
          azPSVersion: "latest"


      # Logout
      - name: logout
        run: |
          az logout
