name: Deploy automation runbooks
on:
  push:
permissions:
  contents: read
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🔑 Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS_MG }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages
        run: |
          pip install azure-cli
          pip install azure.identity
          pip install python-dotenv
          

      - name: execute py script # run policy_assignment.py
        env:
          SUBSCRIPTION_ID: ${{ vars.SUBSCRIPTION_ID }}
          WORKSPACE_ID: ${{ vars.WORKSPACE_ID }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          ASSIGNMENT_LOCATION: ${{ vars.ASSIGNMENT_LOCATION }}
          MANAGEMENT_GROUP: ${{ vars.MANAGEMENT_GROUP }}
        run: 
            python policy_assignments.py
        working-directory: scripts_mg


      # Deploy runbooks
      - name: Deploy Azure runbooks
        uses: azure/powershell@v1
        with:
          inlineScript: |       
            pushd ./scripts_mg
            Import-AzAutomationRunbook -AutomationAccountName ${{ vars.AUTOMATION_ACCOUNT_NAME }} -Name ${{ vars.RUNBOOK_NAME }} -Path remediation_task_runbook.ps1 -Published -ResourceGroupName ${{ vars.RESOURCE_GROUP }} -Type PowerShell
            popd
          azPSVersion: "latest"    

      # Create And link runbook to schedule
      - name: Create And Link Runbook To Schedule
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $params =  @{"identity"="${{ secrets.AUTOMATION_ACCOUNT_IDENTITY }}";"subscription"="${{ vars.SUBSCRIPTION_NAME }}";"managementGroup"="${{ vars.MANAGEMENT_GROUP }}"}
            New-AzAutomationSchedule -AutomationAccountName ${{ vars.AUTOMATION_ACCOUNT_NAME }} -Name ${{ vars.SCHEDULE_NAME }} -StartTime '${{ vars.DATE_START_RUNBOOK }} ${{ vars.TIME_START_RUNBOOK }}' -HourInterval 1 -TimeZone ${{ vars.TIME_ZONE }} -ResourceGroupName ${{ vars.RESOURCE_GROUP }}
            Register-AzAutomationScheduledRunbook -AutomationAccountName ${{ vars.AUTOMATION_ACCOUNT_NAME }} -Parameters $params -RunbookName ${{ vars.RUNBOOK_NAME }} -ScheduleName ${{ vars.SCHEDULE_NAME }} -ResourceGroupName ${{ vars.RESOURCE_GROUP }}
          azPSVersion: "latest"


      # Logout
      - name: logout
        run: |
          az logout